a="I love my girlfriend, NO SHIT!!!"
b="I love my girlfriend, \tNO SHIT!!!"
c="I love my girlfriend {love:.4f}, NO SHIT!!!"
d="I love my girlfriend 3000"
e="I love my girlfriend"
f="3000"
g="i love her"
print("\ncapitalize(): Converts the first character to upper case\n", a.capitalize())
print("\ncasefold(): Converts string into lower case\n", a.casefold())
print("\ncenter(): Returns a centered string\n", a.center(60))
print("\nencode(): Returns an encoded version of the string\n", a.encode())
print("\nendswith(): Returns true if the string ends with the specified value\n", a.endswith("!"))
print("\nexpandtabs(): Sets the tab size of the string\n", b.expandtabs(10))
print("\nfind(): Searches the string for a specified value and returns the position of where it was found\n", a.find("my"))
print("\nformat(): Formats specified values in a string\n", c.format(love=3000))
#format_map()
print("\nindex(): Searches the string for a specified value and returns the position of where it was found\n", a.index("love"))
print("\nisalnum(): Returns True if all characters in the string are alphanumeric\n", d.isalnum())
print("\nisalpha(): Returns True if all characters in the string are in the alphabet\n", e.isalpha())
print("\nisascii(): Returns True if all characters in the string are ascii characters\n", a.isascii())
print("\nisdecimal(): Returns True if all characters in the string are decimals\n", f.isdecimal())
print("\nisdigit(): Returns True if all characters in the string are digits\n", f.isdigit())
print("\nisidentifier(): Returns True if the string is an identifier\n", e.isidentifier())
print("\nislower(): Returns True if all characters in the string are lower case\n", g.islower())
print("\nisnumeric(): Returns True if all characters in the string are numeric\n", f.isnumeric())
print("\nisprintable(): Returns True if all characters in the string are printable\n", c.isprintable())

print("\nisspace(): Returns True if all characters in the string are whitespaces\n", " \t\n".isspace())
print("\nistitle(): Returns True if the string follows the rules of a title\n", a.istitle())
print("\nisupper(): Returns True if all characters in the string are upper case\n", a.isupper())
print("\njoin(): Joins the elements of an iterable to the end of the string\n", ",".join(["I", "love", "my", "girlfriend"]))
print("\nljust(): Returns a left justified version of the string\n", a.ljust(60))
print("\nlower(): Converts a string into lower case\n", a.lower())
print("\nlstrip(): Returns a left trim version of the string\n", "    I love my girlfriend".lstrip())
print("\nmaketrans() and translate(): Returns a translation table to be used in translations\n", a.translate(a.maketrans("I", "1")))
print("\npartition(): Returns a tuple where the string is parted into three parts\n", a.partition("girlfriend"))
print("\nreplace(): Returns a string where a specified value is replaced with a specified value\n", a.replace("girlfriend", "wife"))
print("\nrfind(): Searches the string for a specified value and returns the last position of where it was found\n", a.rfind("I"))
print("\nrindex(): Searches the string for a specified value and returns the last position of where it was found\n", a.rindex("I"))
print("\nrjust(): Returns a right justified version of the string\n", a.rjust(60))
print("\nrpartition(): Returns a tuple where the string is parted into three parts\n", a.rpartition("girlfriend"))
print("\nrsplit(): Splits the string at the specified separator, and returns a list\n", a.rsplit(", "))
print("\nrstrip(): Returns a right trim version of the string\n", "I love my girlfriend    ".rstrip())
print("\nsplit(): Splits the string at the specified separator, and returns a list\n", a.split(", "))
print("\nsplitlines(): Splits the string at line breaks and returns a list\n", "I love my girlfriend\nNO SHIT!!!".splitlines())
print("\nstartswith(): Returns true if the string starts with the specified value\n", a.startswith("I"))
print("\nstrip(): Returns a trimmed version of the string\n", "    I love my girlfriend    ".strip())
print("\nswapcase(): Swaps cases, lower case becomes upper case and vice versa\n", a.swapcase())
print("\ntitle(): Converts the first character of each word to upper case\n", a.title())
print("\nupper(): Converts a string into upper case\n", a.upper())
print("\nzfill(): Fills the string with a specified number of 0 values at the beginning\n", f.zfill(10))
